-- PROGRESSION - 1

-- 1. **Create table city**

CREATE TABLE CITY(
ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

-- 2. **Create table referee**

CREATE TABLE REFEREE(
ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

-- 3. **Create table innings**

CREATE TABLE INNINGS(
ID INT PRIMARY KEY,
INNINGS_NUMBER INT NOT NULL
);

-- 4. **Create table extra_type**

CREATE TABLE EXTRA_TYPE(
ID INT PRIMARY KEY,
NAME VARCHAR(50)NOT NULL
);

-- 5. **Create table skill**

CREATE TABLE SKILL(
ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL
);

-- 6. **Create table team**

CREATE TABLE TEAM(
ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
COACH VARCHAR(50) NOT NULL,
HOME_CITY INT NOT NULL,
CONSTRAINT FK_HOME FOREIGN KEY (HOME_CITY) REFERENCES CITY(ID),
CAPTAIN INT NOT NULL
);


-- 7. **Create table player**

CREATE TABLE PLAYER(
ID INT PRIMARY KEY,
NAME VARCHAR(50) NOT NULL,
COUNTRY VARCHAR(50),
SKILL_ID INT NOT NULL,
CONSTRAINT FK_SKILL FOREIGN KEY (SKILL_ID) REFERENCES SKILL(ID),
TEAM_ID INT NOT NULL,
CONSTRAINT FK_TEAM FOREIGN KEY (TEAM_ID) REFERENCES TEAM(ID)
);

-- 8. **Create table venue**

CREATE TABLE VENUE(
ID INT PRIMARY KEY,
STADIUM_NAME VARCHAR(50) NOT NULL,
CITY_ID INT NOT NULL,
CONSTRAINT FK_VENUE FOREIGN KEY (CITY_ID) REFERENCES CITY(ID)
);

-- 9. **Create table event**

CREATE TABLE EVENT(
ID INT PRIMARY KEY,
INNINGS_ID INT NOT NULL,
CONSTRAINT FK_EVENT FOREIGN KEY (INNINGS_ID) REFERENCES INNINGS(ID),
EVENT_NO INT NOT NULL,
RAIDER_ID INT NOT NULL,
RAIDER_POINT INT NOT NULL,
DEFENDING_POINTS INT NOT NULL,
CLOCK_IN_SECONDS INT NOT NULL,
TEAM_ONE_SCORE INT NOT NULL,
TEAM_TWO_SCORE INT NOT NULL
);

-- 10. **Create table extra_event**

CREATE TABLE EXTRA_EVENT(
ID INT PRIMARY KEY,
EVENT_ID INT  NOT NULL,
CONSTRAINT FK_EVE FOREIGN KEY (EVENT_ID) REFERENCES EVENT(ID),
EXTRA_TYPE_ID INT NOT NULL,
CONSTRAINT FK_TYPE FOREIGN KEY (EXTRA_TYPE_ID) REFERENCES EXTRA_TYPE(ID),
POINTS INT NOT NULL,
SCORING_TEAM_ID INT NOT NULL,
CONSTRAINT FK_SCORE FOREIGN KEY (SCORING_TEAM_ID) REFERENCES TEAM(ID)
);


-- 11. **Create table outcome**

CREATE TABLE OUTCOME (
ID INT PRIMARY KEY,
STATUS VARCHAR(100) NOT NULL,
WINNER_TEAM_ID INT,
CONSTRAINT FK_WINNER FOREIGN KEY (WINNER_TEAM_ID) REFERENCES TEAM(ID),
SCORE INT,
PLAYER_OF_THE_MATCH INT,
CONSTRAINT FK_MATCH FOREIGN KEY (PLAYER_OF_THE_MATCH) REFERENCES PLAYER(ID)
);


-- 12. **Create table game**

CREATE TABLE GAME(
ID INT PRIMARY KEY,
GAME_DATE DATE NOT NULL,
TEAM_ID_1 INT NOT NULL,
CONSTRAINT FK_TEAM1 FOREIGN KEY (TEAM_ID_1) REFERENCES TEAM(ID),
TEAM_ID_2 INT NOT NULL,
CONSTRAINT FK_TEAM2 FOREIGN KEY (TEAM_ID_2) REFERENCES TEAM(ID),
VENUE_ID INT NOT NULL,
CONSTRAINT FK_VENU FOREIGN KEY (VENUE_ID) REFERENCES VENUE(ID),
OUTCOME_ID INT NOT NULL,
CONSTRAINT FK_OUTCOM FOREIGN KEY (OUTCOME_ID) REFERENCES OUTCOME(ID),
REFEREE_ID_1 INT  NOT NULL,
CONSTRAINT FK_ID1 FOREIGN KEY (REFEREE_ID_1) REFERENCES REFEREE(ID),
REFEREE_ID_2 INT NOT NULL,
CONSTRAINT FK_ID2 FOREIGN KEY (REFEREE_ID_2) REFERENCES REFEREE(ID),
FIRST_INNINGS_ID INT NOT NULL,
CONSTRAINT FK_INN1 FOREIGN KEY (FIRST_INNINGS_ID) REFERENCES INNINGS(ID),
SECOND_INNINGS_ID INT NOT NULL,
CONSTRAINT FK_INN2 FOREIGN KEY (SECOND_INNINGS_ID) REFERENCES INNINGS(ID)
);


-- 13. **Drop table city**

DROP TABLE CITY CASCADE CONSTRAINTS;

-- 14. **Drop table innings**
DROP TABLE INNINGS CASCADE CONSTRAINTS;

-- 15. **Drop table skill**

DROP TABLE SKILL CASCADE CONSTRAINTS;

-- 16. **Drop table extra_type**

DROP TABLE EXTRA_TYPE CASCADE CONSTRAINTS;